### ISSUE TITLE
Figuring out the VI format

### ISSUE THREAD

**Issue by mefistotelis** [jcreigh/pylabview#1]
Are you still interested in LabVIEW? Because I could use some help.

I secured some of my time to work on the RSRC format. With some help, I could reach further.

My plan is:
- figure out VCTP block completely
- figure out FPHx block
- figure out default values block
- make a tool which uses VCTP and DFDS to re-create FPHx

https://github.com/mefistotelis/pylabview

**Comment by jcreigh** [comment]
Oh wow. You've really put a ton of work into this. :o

I completely forgot I made those silly little scripts back then. I haven't
used labview in quite awhile, but I still love reverse engineering. I have
a few other projects I'm procrastinating on, but I'll keep my eye on this
and will let you know if I have some time and motivation.

Feel free to reach out by email though :)

>

**Comment by mefistotelis** [comment]
Will do. Thank you! :)
